name: Add PR to Project

on:
  pull_request:
    # types: [opened, reopened, ready_for_review]
    branches:
      - main

jobs:
  add-to-project:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-github-app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Add PR to project
        uses: actions/add-to-project@v1.0.2
        id: add-to-project
        with:
          project-url: https://github.com/users/Himenon/projects/2
          # github-token: ${{ steps.create-github-app-token.outputs.token }}
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}

      - name: Set status to In Progress
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}
          ITEM_ID: ${{ steps.add-to-project.outputs.itemId }}
        run: |
          gh project item-edit --id $ITEM_ID --field-id PVTSSF_lAHOAGZ3Xc4BLIWAzg6y8i0 --project-id PVT_kwHOAGZ3Xc4BLIWA --single-select-option-id 47fc9ee4
